-- Migration 043: Catálogo de tipos de projeto (Feature #65, parte 1) +
-- fingerprint de spec para REUSO SILENCIOSO (Feature #65, parte 2).
--
-- NOTA IMPORTANTE sobre o formato: o runner de migrations (db/init.ts) faz split
-- ingênuo por ';' e remove linhas que começam com '--'. Por isso, nenhum literal de
-- string abaixo contém ';' nem aspas simples, e os templates usam strings de escape
-- E'...' com \n (uma linha física por template) em vez de quebras reais.
--
-- ── Parte 2: fingerprint (reuso silencioso, intra-tenant) ──────────────────────
-- spec_fingerprint = SHA-256 do conteúdo NORMALIZADO das specs (ver
-- projectCreation.ts::computeSpecFingerprint). Usado para detectar, no momento da
-- criação, um projeto anterior do MESMO tenant com a mesma spec, e reaproveitar
-- artefatos/estrutura. NUNCA cruza tenants. NULL para projetos legados.
ALTER TABLE projects ADD COLUMN IF NOT EXISTS spec_fingerprint TEXT;

CREATE INDEX IF NOT EXISTS idx_projects_tenant_fingerprint
  ON projects (tenant_id, spec_fingerprint)
  WHERE spec_fingerprint IS NOT NULL;

-- ── Parte 1: catálogo de SPECs pré-prontas categorizadas ───────────────────────
-- Este é um STARTER SET honesto e extensível (dezenas de tipos cobrindo categorias
-- BR e do mundo). A infraestrutura (tabela + rotas GET /api/catalog e
-- POST /api/catalog/:slug/use) suporta crescer para a ordem de ~1000 tipos sem
-- mudança de schema: basta inserir novas linhas aqui (ou por seed adicional).
CREATE TABLE IF NOT EXISTS spec_catalog (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug              TEXT NOT NULL UNIQUE,
  title             TEXT NOT NULL,
  category          TEXT NOT NULL,
  description       TEXT NOT NULL DEFAULT '',
  template_markdown TEXT NOT NULL,
  tags              TEXT[] NOT NULL DEFAULT '{}',
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_spec_catalog_category ON spec_catalog(category);

INSERT INTO spec_catalog (slug, title, category, description, template_markdown, tags) VALUES
('todo-list', 'Lista de tarefas', 'Simples', 'App simples de tarefas com autenticação e marcação de conclusão.', E'# Lista de tarefas\n\n## Objetivo\nGerenciar tarefas pessoais com autenticação de usuário.\n\n## Personas\n- Usuário final que organiza suas tarefas.\n\n## Requisitos funcionais\n- FR-01 Cadastro e login de usuário.\n- FR-02 Criar, editar, concluir e excluir tarefas.\n- FR-03 Filtrar por concluídas e pendentes.\n\n## Modelo de dados\n- users (id, email, senha_hash)\n- tasks (id, user_id, titulo, feita, criada_em)\n\n## Stack sugerida\n- Backend Node com Postgres.', ARRAY['simples','crud','tarefas']),
('link-in-bio', 'Página de links (link in bio)', 'Simples', 'Página pública de links estilo linktree com painel de edição.', E'# Página de links\n\n## Objetivo\nExibir uma página pública com links e um painel para editar.\n\n## Personas\n- Criador de conteúdo que compartilha links.\n\n## Requisitos funcionais\n- FR-01 Página pública responsiva com avatar e links.\n- FR-02 Painel autenticado para adicionar e reordenar links.\n- FR-03 Métrica de cliques por link.\n\n## Modelo de dados\n- pages (id, slug, titulo, avatar_url)\n- links (id, page_id, rotulo, url, ordem, cliques)\n\n## Stack sugerida\n- Fullstack web com Next.', ARRAY['simples','landing','links']),
('url-shortener', 'Encurtador de URLs', 'Simples', 'Serviço de encurtamento de links com estatísticas de acesso.', E'# Encurtador de URLs\n\n## Objetivo\nGerar URLs curtas e redirecionar registrando acessos.\n\n## Requisitos funcionais\n- FR-01 Criar código curto para uma URL longa.\n- FR-02 Redirecionar do código curto para a URL original.\n- FR-03 Contabilizar acessos por código.\n\n## Modelo de dados\n- links (id, codigo, url_original, criado_em)\n- hits (id, link_id, acessado_em, ip)\n\n## Stack sugerida\n- Backend Node com Postgres e cache.', ARRAY['simples','api','links']),
('crm-vendas', 'CRM de vendas', 'CRM', 'Gestão de leads, contatos e funil de vendas com atividades.', E'# CRM de vendas\n\n## Objetivo\nGerenciar leads e oportunidades ao longo de um funil de vendas.\n\n## Personas\n- Vendedor que registra contatos e negociações.\n- Gestor que acompanha o funil.\n\n## Requisitos funcionais\n- FR-01 Cadastro de contas, contatos e leads.\n- FR-02 Funil com estágios configuráveis e arrastar cartões.\n- FR-03 Atividades e lembretes por oportunidade.\n- FR-04 Relatório de conversão por estágio.\n\n## Modelo de dados\n- accounts, contacts, deals (estagio, valor), activities\n\n## Stack sugerida\n- Fullstack SaaS multiusuário.', ARRAY['crm','vendas','funil']),
('helpdesk-tickets', 'Helpdesk de tickets', 'CRM', 'Central de atendimento com tickets, filas e SLA.', E'# Helpdesk de tickets\n\n## Objetivo\nReceber e resolver chamados de suporte com controle de SLA.\n\n## Requisitos funcionais\n- FR-01 Abertura de ticket por cliente com categoria e prioridade.\n- FR-02 Filas e atribuição a atendentes.\n- FR-03 Histórico de mensagens por ticket.\n- FR-04 Indicadores de SLA e tempo de resolução.\n\n## Modelo de dados\n- tickets, ticket_messages, agents, queues\n\n## Stack sugerida\n- Fullstack SaaS.', ARRAY['crm','suporte','sla']),
('fintech-wallet', 'Carteira digital', 'Fintech', 'Carteira com saldo, transferências e extrato.', E'# Carteira digital\n\n## Objetivo\nPermitir depósitos, transferências entre usuários e extrato.\n\n## Requisitos funcionais\n- FR-01 Conta com saldo por usuário.\n- FR-02 Transferência entre contas com idempotência.\n- FR-03 Extrato paginado de lançamentos.\n- FR-04 Ledger com dupla entrada e trilha de auditoria.\n\n## Modelo de dados\n- accounts, ledger_entries, transfers\n\n## Notas\n- PII e dados sensíveis restritos, nunca em log.\n\n## Stack sugerida\n- Backend Node com Postgres transacional.', ARRAY['fintech','pagamentos','ledger']),
('pix-cobranca', 'Cobranças Pix', 'Fintech', 'Emissão de cobranças Pix com QR Code e conciliação.', E'# Cobranças Pix\n\n## Objetivo\nEmitir cobranças Pix, gerar QR Code e conciliar pagamentos.\n\n## Requisitos funcionais\n- FR-01 Criar cobrança com valor e vencimento.\n- FR-02 Gerar payload e QR Code Pix.\n- FR-03 Webhook de confirmação de pagamento.\n- FR-04 Conciliação e status pago ou vencido.\n\n## Modelo de dados\n- charges (id, valor, status, txid), payments\n\n## Stack sugerida\n- Backend Node integrando provedor de pagamentos.', ARRAY['fintech','pix','brasil']),
('ecommerce-loja', 'Loja e-commerce', 'E-commerce', 'Loja online completa com catálogo, carrinho e checkout.', E'# Loja e-commerce\n\n## Objetivo\nVender produtos online com carrinho e checkout.\n\n## Personas\n- Comprador que navega e finaliza pedido.\n- Lojista que cadastra produtos.\n\n## Requisitos funcionais\n- FR-01 Catálogo com categorias e busca.\n- FR-02 Carrinho e checkout com cálculo de frete.\n- FR-03 Pedidos e status de entrega.\n- FR-04 Painel do lojista para estoque e preços.\n\n## Modelo de dados\n- products, categories, carts, orders, order_items\n\n## Stack sugerida\n- Fullstack e-commerce.', ARRAY['ecommerce','loja','carrinho']),
('marketplace-multi', 'Marketplace multivendedor', 'E-commerce', 'Marketplace com múltiplos vendedores e comissões.', E'# Marketplace multivendedor\n\n## Objetivo\nConectar múltiplos vendedores e compradores com repasse de comissão.\n\n## Requisitos funcionais\n- FR-01 Cadastro de vendedores e suas lojas.\n- FR-02 Catálogo agregado por vendedor.\n- FR-03 Pedido com split de pagamento e comissão.\n- FR-04 Painel de repasses ao vendedor.\n\n## Modelo de dados\n- sellers, stores, products, orders, payouts\n\n## Stack sugerida\n- Fullstack marketplace.', ARRAY['ecommerce','marketplace','comissao']),
('assinatura-recorrente', 'Assinaturas recorrentes', 'E-commerce', 'Plataforma de assinatura com planos e cobrança recorrente.', E'# Assinaturas recorrentes\n\n## Objetivo\nGerenciar planos e cobranças recorrentes de assinantes.\n\n## Requisitos funcionais\n- FR-01 Planos com preço e ciclo.\n- FR-02 Assinatura, upgrade e cancelamento.\n- FR-03 Cobrança recorrente e retentativa em falha.\n- FR-04 Portal do assinante.\n\n## Modelo de dados\n- plans, subscriptions, invoices\n\n## Stack sugerida\n- Fullstack SaaS com worker de cobrança.', ARRAY['ecommerce','assinatura','saas']),
('logistica-rastreio', 'Rastreamento de entregas', 'Logística', 'Rastreamento de pedidos e status de entrega em tempo real.', E'# Rastreamento de entregas\n\n## Objetivo\nAcompanhar entregas com eventos de status por pedido.\n\n## Requisitos funcionais\n- FR-01 Ingestão de eventos de status por transportadora.\n- FR-02 Linha do tempo de rastreio por pedido.\n- FR-03 Página pública de rastreio por código.\n- FR-04 Notificação ao cliente em cada evento.\n\n## Modelo de dados\n- shipments, tracking_events\n\n## Stack sugerida\n- Backend event-driven com fila.', ARRAY['logistica','rastreio','entregas']),
('gestao-frota', 'Gestão de frota', 'Logística', 'Controle de veículos, motoristas e manutenção.', E'# Gestão de frota\n\n## Objetivo\nControlar veículos, motoristas e ordens de manutenção.\n\n## Requisitos funcionais\n- FR-01 Cadastro de veículos e motoristas.\n- FR-02 Registro de abastecimento e quilometragem.\n- FR-03 Ordens de manutenção preventiva e corretiva.\n- FR-04 Alertas de vencimento de documentos.\n\n## Modelo de dados\n- vehicles, drivers, maintenance_orders, fuel_logs\n\n## Stack sugerida\n- Fullstack interno.', ARRAY['logistica','frota','manutencao']),
('saude-agendamento', 'Agendamento de consultas', 'Saúde', 'Agenda de consultas médicas com profissionais e horários.', E'# Agendamento de consultas\n\n## Objetivo\nAgendar consultas entre pacientes e profissionais de saúde.\n\n## Requisitos funcionais\n- FR-01 Cadastro de profissionais e especialidades.\n- FR-02 Agenda com horários disponíveis e bloqueio de conflitos.\n- FR-03 Agendamento e cancelamento pelo paciente.\n- FR-04 Lembrete por mensagem antes da consulta.\n\n## Modelo de dados\n- professionals, patients, slots, appointments\n\n## Stack sugerida\n- Fullstack com notificações.', ARRAY['saude','agenda','consultas']),
('prontuario-clinica', 'Prontuário de clínica', 'Saúde', 'Prontuário eletrônico com histórico clínico e anexos.', E'# Prontuário de clínica\n\n## Objetivo\nRegistrar histórico clínico do paciente com segurança.\n\n## Requisitos funcionais\n- FR-01 Ficha do paciente com dados e alergias.\n- FR-02 Evoluções por atendimento.\n- FR-03 Anexos de exames.\n- FR-04 Controle de acesso por profissional.\n\n## Notas\n- Dados de saúde são sensíveis, restritos e auditados.\n\n## Modelo de dados\n- patients, encounters, attachments\n\n## Stack sugerida\n- Fullstack com controle de acesso.', ARRAY['saude','prontuario','lgpd']),
('educacao-lms', 'Plataforma EAD (LMS)', 'Educação', 'Cursos online com aulas, matrículas e progresso.', E'# Plataforma EAD\n\n## Objetivo\nOferecer cursos com aulas, matrículas e acompanhamento de progresso.\n\n## Requisitos funcionais\n- FR-01 Catálogo de cursos e módulos.\n- FR-02 Matrícula e controle de acesso ao conteúdo.\n- FR-03 Player de aula e marcação de conclusão.\n- FR-04 Certificado ao concluir o curso.\n\n## Modelo de dados\n- courses, modules, lessons, enrollments, progress\n\n## Stack sugerida\n- Fullstack SaaS.', ARRAY['educacao','ead','lms']),
('quiz-avaliacao', 'Quiz e avaliações', 'Educação', 'Criação de quizzes com correção automática e notas.', E'# Quiz e avaliações\n\n## Objetivo\nCriar avaliações com questões e correção automática.\n\n## Requisitos funcionais\n- FR-01 Banco de questões por assunto.\n- FR-02 Montagem de prova e tempo limite.\n- FR-03 Correção automática e nota final.\n- FR-04 Relatório de desempenho por aluno.\n\n## Modelo de dados\n- questions, quizzes, attempts, answers\n\n## Stack sugerida\n- Fullstack.', ARRAY['educacao','quiz','avaliacao']),
('rh-recrutamento', 'Recrutamento e seleção', 'RH', 'Pipeline de vagas e candidatos com etapas de entrevista.', E'# Recrutamento e seleção\n\n## Objetivo\nGerenciar vagas e candidatos em um pipeline de contratação.\n\n## Requisitos funcionais\n- FR-01 Publicação de vagas.\n- FR-02 Cadastro de candidatos e currículo.\n- FR-03 Pipeline com etapas e feedback.\n- FR-04 Relatório de tempo de contratação.\n\n## Modelo de dados\n- jobs, candidates, applications, stages\n\n## Stack sugerida\n- Fullstack SaaS.', ARRAY['rh','recrutamento','ats']),
('rh-ponto', 'Controle de ponto', 'RH', 'Registro de jornada com marcações e banco de horas.', E'# Controle de ponto\n\n## Objetivo\nRegistrar entradas e saídas e apurar banco de horas.\n\n## Requisitos funcionais\n- FR-01 Marcação de ponto por colaborador.\n- FR-02 Escalas e jornada esperada.\n- FR-03 Apuração de horas extras e faltas.\n- FR-04 Espelho de ponto exportável.\n\n## Modelo de dados\n- employees, punches, schedules\n\n## Stack sugerida\n- Fullstack interno.', ARRAY['rh','ponto','jornada']),
('imob-anuncios', 'Portal imobiliário', 'Imobiliário', 'Anúncios de imóveis com busca por filtros e contato.', E'# Portal imobiliário\n\n## Objetivo\nPublicar imóveis e conectar interessados a corretores.\n\n## Requisitos funcionais\n- FR-01 Cadastro de imóveis com fotos e características.\n- FR-02 Busca por filtros de preço, bairro e tipo.\n- FR-03 Contato e agendamento de visita.\n- FR-04 Painel do corretor.\n\n## Modelo de dados\n- properties, media, leads, agents\n\n## Stack sugerida\n- Fullstack.', ARRAY['imobiliario','anuncios','busca']),
('marketing-newsletter', 'Newsletter e campanhas', 'Marketing', 'Envio de e-mails em massa com listas e métricas.', E'# Newsletter e campanhas\n\n## Objetivo\nGerenciar listas e enviar campanhas de e-mail com métricas.\n\n## Requisitos funcionais\n- FR-01 Listas e inscritos com opt-in.\n- FR-02 Editor de campanha e agendamento.\n- FR-03 Envio em massa via fila.\n- FR-04 Métricas de abertura e clique.\n\n## Modelo de dados\n- lists, subscribers, campaigns, events\n\n## Stack sugerida\n- Backend com worker de envio.', ARRAY['marketing','email','campanhas']),
('produtividade-kanban', 'Quadro Kanban', 'Produtividade', 'Gestão de projetos em quadros, colunas e cartões.', E'# Quadro Kanban\n\n## Objetivo\nOrganizar trabalho em quadros com colunas e cartões arrastáveis.\n\n## Requisitos funcionais\n- FR-01 Quadros, colunas e cartões.\n- FR-02 Arrastar cartões entre colunas.\n- FR-03 Etiquetas, responsáveis e prazos.\n- FR-04 Comentários por cartão.\n\n## Modelo de dados\n- boards, columns, cards, labels\n\n## Stack sugerida\n- Fullstack colaborativo.', ARRAY['produtividade','kanban','projetos']),
('notas-markdown', 'Notas em Markdown', 'Produtividade', 'App de notas com edição em Markdown e busca.', E'# Notas em Markdown\n\n## Objetivo\nCriar e organizar notas com edição em Markdown.\n\n## Requisitos funcionais\n- FR-01 Criar, editar e excluir notas.\n- FR-02 Preview de Markdown.\n- FR-03 Busca por conteúdo e etiquetas.\n- FR-04 Sincronização por usuário.\n\n## Modelo de dados\n- notes, tags, note_tags\n\n## Stack sugerida\n- Fullstack.', ARRAY['produtividade','notas','markdown']),
('gov-protocolo', 'Protocolo de processos', 'Governo BR', 'Abertura e tramitação de processos administrativos.', E'# Protocolo de processos\n\n## Objetivo\nRegistrar e tramitar processos administrativos com número de protocolo.\n\n## Requisitos funcionais\n- FR-01 Abertura de processo com número único.\n- FR-02 Tramitação entre setores.\n- FR-03 Anexos e despachos.\n- FR-04 Consulta pública por protocolo.\n\n## Modelo de dados\n- processes, movements, attachments, departments\n\n## Stack sugerida\n- Fullstack interno com trilha de auditoria.', ARRAY['governo','brasil','processos']),
('nfe-emissor', 'Emissor de notas fiscais', 'Governo BR', 'Emissão e gestão de notas fiscais eletrônicas.', E'# Emissor de notas fiscais\n\n## Objetivo\nEmitir e armazenar notas fiscais eletrônicas.\n\n## Requisitos funcionais\n- FR-01 Cadastro de emitentes e produtos.\n- FR-02 Emissão de nota com itens e impostos.\n- FR-03 Armazenamento do documento e status.\n- FR-04 Consulta e cancelamento.\n\n## Modelo de dados\n- issuers, invoices, invoice_items\n\n## Notas\n- Integração com provedor fiscal fora do escopo inicial.\n\n## Stack sugerida\n- Backend Node.', ARRAY['governo','brasil','fiscal']),
('social-feed', 'Rede social com feed', 'Social', 'Feed de publicações com curtidas, comentários e seguir.', E'# Rede social com feed\n\n## Objetivo\nPermitir publicar, curtir, comentar e seguir usuários.\n\n## Requisitos funcionais\n- FR-01 Perfil e seguir usuários.\n- FR-02 Publicar texto e imagem.\n- FR-03 Feed cronológico dos seguidos.\n- FR-04 Curtidas e comentários.\n\n## Modelo de dados\n- users, posts, follows, likes, comments\n\n## Stack sugerida\n- Fullstack com cache de feed.', ARRAY['social','feed','comunidade']),
('chat-tempo-real', 'Chat em tempo real', 'Social', 'Mensagens em tempo real com salas e presença.', E'# Chat em tempo real\n\n## Objetivo\nTrocar mensagens em tempo real em salas com indicador de presença.\n\n## Requisitos funcionais\n- FR-01 Salas e mensagens em tempo real.\n- FR-02 Indicador de digitando e presença.\n- FR-03 Histórico persistente por sala.\n- FR-04 Notificação de nova mensagem.\n\n## Modelo de dados\n- rooms, messages, memberships\n\n## Stack sugerida\n- Backend WebSocket com Postgres.', ARRAY['social','chat','realtime']),
('iot-telemetria', 'Telemetria IoT', 'IoT', 'Ingestão de leituras de sensores e dashboards.', E'# Telemetria IoT\n\n## Objetivo\nColetar leituras de sensores e exibir em dashboards.\n\n## Requisitos funcionais\n- FR-01 Ingestão de leituras por dispositivo.\n- FR-02 Séries temporais por métrica.\n- FR-03 Alertas por limiar.\n- FR-04 Dashboard com gráficos.\n\n## Modelo de dados\n- devices, readings, alerts\n\n## Stack sugerida\n- Backend de ingestão com fila e séries temporais.', ARRAY['iot','sensores','telemetria']),
('dados-etl', 'Pipeline de dados ETL', 'IA e Dados', 'Extração, transformação e carga de dados agendada.', E'# Pipeline de dados ETL\n\n## Objetivo\nExtrair dados de fontes, transformar e carregar em destino.\n\n## Requisitos funcionais\n- FR-01 Conectores de origem configuráveis.\n- FR-02 Transformações e validação de qualidade.\n- FR-03 Agendamento e reprocessamento.\n- FR-04 Monitoramento de execuções.\n\n## Modelo de dados\n- sources, jobs, runs, datasets\n\n## Stack sugerida\n- Backend Python com orquestrador.', ARRAY['dados','etl','pipeline']),
('rag-chatbot', 'Chatbot com RAG', 'IA e Dados', 'Assistente que responde sobre documentos via RAG.', E'# Chatbot com RAG\n\n## Objetivo\nResponder perguntas sobre uma base de documentos usando recuperação aumentada.\n\n## Requisitos funcionais\n- FR-01 Ingestão e chunking de documentos.\n- FR-02 Indexação vetorial e busca semântica.\n- FR-03 Resposta com citação das fontes.\n- FR-04 Histórico de conversa por usuário.\n\n## Modelo de dados\n- documents, chunks, embeddings, conversations\n\n## Stack sugerida\n- Backend Python com banco vetorial.', ARRAY['ia','rag','chatbot']),
('reservas-restaurante', 'Reservas de restaurante', 'Serviços', 'Reserva de mesas com horários e capacidade.', E'# Reservas de restaurante\n\n## Objetivo\nGerenciar reservas de mesas respeitando capacidade e horários.\n\n## Requisitos funcionais\n- FR-01 Configuração de mesas e horários.\n- FR-02 Reserva pelo cliente com confirmação.\n- FR-03 Controle de capacidade e overbooking.\n- FR-04 Lembrete e cancelamento.\n\n## Modelo de dados\n- tables, reservations, time_slots\n\n## Stack sugerida\n- Fullstack.', ARRAY['servicos','reservas','restaurante']),
('eventos-ingressos', 'Venda de ingressos', 'Serviços', 'Eventos com lotes de ingressos e check-in.', E'# Venda de ingressos\n\n## Objetivo\nVender ingressos de eventos por lote e validar entrada.\n\n## Requisitos funcionais\n- FR-01 Cadastro de eventos e lotes.\n- FR-02 Compra de ingresso e emissão de QR Code.\n- FR-03 Check-in na entrada por leitura de QR Code.\n- FR-04 Relatório de vendas por evento.\n\n## Modelo de dados\n- events, ticket_batches, tickets, checkins\n\n## Stack sugerida\n- Fullstack.', ARRAY['servicos','eventos','ingressos']),
('agendamento-servicos', 'Agendamento de serviços', 'Serviços', 'Marcação de horários para prestadores de serviço.', E'# Agendamento de serviços\n\n## Objetivo\nAgendar horários entre clientes e prestadores de serviço.\n\n## Requisitos funcionais\n- FR-01 Cadastro de prestadores e serviços.\n- FR-02 Agenda com horários e duração.\n- FR-03 Agendamento com prevenção de conflito.\n- FR-04 Lembrete ao cliente.\n\n## Modelo de dados\n- providers, services, bookings\n\n## Stack sugerida\n- Fullstack com notificações.', ARRAY['servicos','agenda','booking']),
('financeiro-pessoal', 'Finanças pessoais', 'Fintech', 'Controle de receitas, despesas e categorias.', E'# Finanças pessoais\n\n## Objetivo\nRegistrar receitas e despesas com categorias e relatórios.\n\n## Requisitos funcionais\n- FR-01 Lançamentos de receita e despesa.\n- FR-02 Categorias e contas.\n- FR-03 Relatório mensal por categoria.\n- FR-04 Metas de gasto.\n\n## Modelo de dados\n- accounts, transactions, categories, budgets\n\n## Stack sugerida\n- Fullstack.', ARRAY['fintech','financas','pessoal']),
('estoque-pdv', 'Estoque e PDV', 'E-commerce', 'Controle de estoque com ponto de venda.', E'# Estoque e PDV\n\n## Objetivo\nControlar estoque e registrar vendas no ponto de venda.\n\n## Requisitos funcionais\n- FR-01 Cadastro de produtos e saldo de estoque.\n- FR-02 Entrada e saída de estoque.\n- FR-03 Venda no PDV com baixa automática.\n- FR-04 Relatório de giro e ruptura.\n\n## Modelo de dados\n- products, stock_moves, sales, sale_items\n\n## Stack sugerida\n- Fullstack.', ARRAY['ecommerce','estoque','pdv']),
('blog-cms', 'Blog com CMS', 'Conteúdo', 'Blog com editor de posts, categorias e SEO.', E'# Blog com CMS\n\n## Objetivo\nPublicar e gerenciar artigos com categorias e SEO.\n\n## Requisitos funcionais\n- FR-01 Editor de posts com rascunho e publicação.\n- FR-02 Categorias e etiquetas.\n- FR-03 Página pública com SEO e sitemap.\n- FR-04 Comentários moderados.\n\n## Modelo de dados\n- posts, categories, tags, comments\n\n## Stack sugerida\n- Fullstack web.', ARRAY['conteudo','blog','cms']),
('portfolio-institucional', 'Site institucional', 'Conteúdo', 'Site institucional com páginas e formulário de contato.', E'# Site institucional\n\n## Objetivo\nApresentar a empresa com páginas e captação de contato.\n\n## Requisitos funcionais\n- FR-01 Páginas de home, sobre e serviços.\n- FR-02 Formulário de contato com envio de e-mail.\n- FR-03 SEO e desempenho.\n- FR-04 Conteúdo editável.\n\n## Modelo de dados\n- pages, leads\n\n## Stack sugerida\n- Frontend com backend leve para contato.', ARRAY['conteudo','institucional','landing'])
ON CONFLICT (slug) DO NOTHING;
