-- Migration 051: Expansao do catalogo de tipos de projeto (Feature #65) — 2a leva.
--
-- NOTA DE FORMATO (identica a 043): o runner de migrations (db/init.ts) faz split
-- ingenuo por ';' e remove linhas iniciadas por '--'. Por isso NENHUM literal abaixo
-- contem ';' nem aspas simples ('). Os templates usam strings de escape E'...' com \n
-- (uma linha fisica por template) em vez de quebras reais. ON CONFLICT torna idempotente.
--
-- Esta leva dobra o starter set (37 -> 73) e introduz categorias novas:
-- Juridico, Agro, Turismo, Alimentacao, Esportes e ONG.
INSERT INTO spec_catalog (slug, title, category, description, template_markdown, tags) VALUES
('open-finance-agregador', 'Agregador Open Finance', 'Fintech', 'Consolida contas e transacoes de multiplos bancos via Open Finance.', E'# Agregador Open Finance\n\n## Objetivo\nConsolidar saldos e transacoes de varias instituicoes em uma visao unica.\n\n## Personas\n- Usuario que conecta suas contas bancarias.\n- Analista que categoriza gastos.\n\n## Requisitos funcionais\n- FR-01 Conexao de contas via consentimento Open Finance.\n- FR-02 Sincronizacao periodica de saldos e transacoes.\n- FR-03 Categorizacao automatica de lancamentos.\n- FR-04 Visao consolidada por conta e categoria.\n\n## Modelo de dados\n- connections, accounts, transactions, categories\n\n## Notas\n- Dados financeiros e PII restritos, nunca em log.\n\n## Stack sugerida\n- Backend Node com worker de sincronizacao.', ARRAY['fintech','open-finance','agregador']),
('emprestimo-p2p', 'Emprestimos P2P', 'Fintech', 'Plataforma de emprestimo entre pessoas com analise e repasse.', E'# Emprestimos P2P\n\n## Objetivo\nConectar tomadores e investidores com analise de credito e repasse.\n\n## Requisitos funcionais\n- FR-01 Solicitacao de emprestimo com score de credito.\n- FR-02 Oferta de investidores e montagem de lastro.\n- FR-03 Contrato e cronograma de parcelas.\n- FR-04 Cobranca e repasse aos investidores.\n\n## Modelo de dados\n- borrowers, investors, loans, installments\n\n## Stack sugerida\n- Backend Node com ledger transacional.', ARRAY['fintech','credito','p2p']),
('cartoes-corporativos', 'Cartoes corporativos', 'Fintech', 'Gestao de despesas com cartoes corporativos e prestacao de contas.', E'# Cartoes corporativos\n\n## Objetivo\nControlar limites, transacoes e prestacao de contas de cartoes da empresa.\n\n## Requisitos funcionais\n- FR-01 Emissao de cartoes virtuais por colaborador.\n- FR-02 Limites e politicas de gasto por centro de custo.\n- FR-03 Anexo de comprovante por transacao.\n- FR-04 Relatorio de despesas e aprovacao.\n\n## Modelo de dados\n- cards, transactions, receipts, cost_centers\n\n## Stack sugerida\n- Fullstack SaaS.', ARRAY['fintech','despesas','cartoes']),
('ia-geracao-imagens', 'Geracao de imagens com IA', 'IA e Dados', 'Estudio que gera e edita imagens a partir de prompts.', E'# Geracao de imagens com IA\n\n## Objetivo\nGerar e editar imagens a partir de descricoes em linguagem natural.\n\n## Requisitos funcionais\n- FR-01 Geracao de imagem por prompt com parametros.\n- FR-02 Galeria de resultados por usuario.\n- FR-03 Edicao por mascara e variacoes.\n- FR-04 Controle de creditos por uso.\n\n## Modelo de dados\n- generations, assets, credits\n\n## Stack sugerida\n- Backend com fila de inferencia e storage de objetos.', ARRAY['ia','imagens','generativa']),
('agentes-automacao', 'Automacao com agentes de IA', 'IA e Dados', 'Orquestra agentes que executam tarefas com ferramentas.', E'# Automacao com agentes de IA\n\n## Objetivo\nExecutar fluxos autonomos com agentes que usam ferramentas e memoria.\n\n## Requisitos funcionais\n- FR-01 Definicao de agentes com ferramentas e objetivos.\n- FR-02 Execucao de tarefas em fluxo com passos.\n- FR-03 Registro de rastros e custos por execucao.\n- FR-04 Aprovacao humana em passos sensiveis.\n\n## Modelo de dados\n- agents, tools, runs, steps\n\n## Stack sugerida\n- Backend com orquestrador de agentes e fila.', ARRAY['ia','agentes','automacao']),
('bi-dashboards', 'BI e dashboards analiticos', 'IA e Dados', 'Painel analitico com metricas, filtros e series temporais.', E'# BI e dashboards analiticos\n\n## Objetivo\nExibir metricas de negocio em dashboards com filtros e series.\n\n## Requisitos funcionais\n- FR-01 Conectores de fonte e modelagem de metricas.\n- FR-02 Dashboards com graficos e filtros.\n- FR-03 Series temporais e comparativos de periodo.\n- FR-04 Compartilhamento e permissao por painel.\n\n## Modelo de dados\n- datasets, metrics, dashboards, widgets\n\n## Stack sugerida\n- Backend analitico com cache de consultas.', ARRAY['dados','bi','dashboards']),
('transcricao-audio', 'Transcricao e resumo de audio', 'IA e Dados', 'Transcreve reunioes e gera resumos e itens de acao.', E'# Transcricao e resumo de audio\n\n## Objetivo\nTranscrever audios e gerar resumos com itens de acao.\n\n## Requisitos funcionais\n- FR-01 Upload de audio e transcricao automatica.\n- FR-02 Diarizacao por locutor.\n- FR-03 Resumo e extracao de tarefas.\n- FR-04 Busca no texto transcrito.\n\n## Modelo de dados\n- recordings, transcripts, summaries, action_items\n\n## Stack sugerida\n- Backend com fila de transcricao e IA.', ARRAY['ia','transcricao','reunioes']),
('telemedicina', 'Telemedicina', 'Saude', 'Teleconsulta por video com prontuario e receita digital.', E'# Telemedicina\n\n## Objetivo\nRealizar teleconsultas por video com registro clinico e receita digital.\n\n## Requisitos funcionais\n- FR-01 Agenda e sala de video por consulta.\n- FR-02 Prontuario da teleconsulta.\n- FR-03 Emissao de receita e atestado digital.\n- FR-04 Pagamento da consulta.\n\n## Notas\n- Dados de saude sensiveis, restritos e auditados.\n\n## Modelo de dados\n- professionals, patients, appointments, prescriptions\n\n## Stack sugerida\n- Fullstack com video e controle de acesso.', ARRAY['saude','telemedicina','video']),
('farmacia-delivery', 'Farmacia com delivery', 'Saude', 'Catalogo de medicamentos com receita e entrega.', E'# Farmacia com delivery\n\n## Objetivo\nVender medicamentos com validacao de receita e entrega ao cliente.\n\n## Requisitos funcionais\n- FR-01 Catalogo com controle de itens sob receita.\n- FR-02 Upload e validacao de receita.\n- FR-03 Carrinho, pagamento e entrega.\n- FR-04 Historico de compras do cliente.\n\n## Modelo de dados\n- products, prescriptions, orders, deliveries\n\n## Stack sugerida\n- Fullstack e-commerce com regras de receita.', ARRAY['saude','farmacia','delivery']),
('gamificacao-aprendizado', 'Aprendizado gamificado', 'Educacao', 'Trilhas de estudo com pontos, niveis e conquistas.', E'# Aprendizado gamificado\n\n## Objetivo\nEngajar alunos com trilhas, pontos, niveis e conquistas.\n\n## Requisitos funcionais\n- FR-01 Trilhas de licoes com pre-requisitos.\n- FR-02 Pontos e experiencia por atividade.\n- FR-03 Conquistas e ranking.\n- FR-04 Sequencia diaria de estudo.\n\n## Modelo de dados\n- tracks, lessons, points, achievements\n\n## Stack sugerida\n- Fullstack com regras de gamificacao.', ARRAY['educacao','gamificacao','engajamento']),
('gestao-escolar', 'Gestao escolar', 'Educacao', 'Secretaria escolar com matriculas, turmas e boletim.', E'# Gestao escolar\n\n## Objetivo\nGerenciar matriculas, turmas, notas e frequencia de alunos.\n\n## Requisitos funcionais\n- FR-01 Cadastro de alunos, turmas e professores.\n- FR-02 Matricula e alocacao em turmas.\n- FR-03 Lancamento de notas e frequencia.\n- FR-04 Boletim e comunicados aos responsaveis.\n\n## Modelo de dados\n- students, classes, teachers, grades, attendance\n\n## Stack sugerida\n- Fullstack interno.', ARRAY['educacao','escola','secretaria']),
('clube-assinatura-box', 'Clube de assinatura (box)', 'E-commerce', 'Assinatura de boxes recorrentes com curadoria e envio.', E'# Clube de assinatura box\n\n## Objetivo\nGerenciar assinaturas de boxes recorrentes com curadoria e logistica.\n\n## Requisitos funcionais\n- FR-01 Planos de box com ciclo de envio.\n- FR-02 Assinatura, pausa e cancelamento.\n- FR-03 Curadoria de itens por ciclo.\n- FR-04 Geracao de remessa e etiqueta.\n\n## Modelo de dados\n- plans, subscriptions, boxes, shipments\n\n## Stack sugerida\n- Fullstack com worker de cobranca e logistica.', ARRAY['ecommerce','assinatura','box']),
('dropshipping', 'Loja dropshipping', 'E-commerce', 'Loja que repassa pedidos a fornecedores sem estoque proprio.', E'# Loja dropshipping\n\n## Objetivo\nVender produtos repassando o pedido a fornecedores sem estoque proprio.\n\n## Requisitos funcionais\n- FR-01 Importacao de produtos de fornecedores.\n- FR-02 Catalogo e checkout ao cliente.\n- FR-03 Repasse automatico do pedido ao fornecedor.\n- FR-04 Sincronizacao de estoque e rastreio.\n\n## Modelo de dados\n- suppliers, products, orders, fulfillments\n\n## Stack sugerida\n- Fullstack e-commerce com integracoes.', ARRAY['ecommerce','dropshipping','fornecedores']),
('roteirizacao-entregas', 'Roteirizacao de entregas', 'Logistica', 'Otimiza rotas de entrega por veiculo e janela.', E'# Roteirizacao de entregas\n\n## Objetivo\nMontar e otimizar rotas de entrega respeitando janelas e capacidade.\n\n## Requisitos funcionais\n- FR-01 Cadastro de paradas com endereco e janela.\n- FR-02 Alocacao por veiculo e capacidade.\n- FR-03 Otimizacao de sequencia de paradas.\n- FR-04 Acompanhamento do motorista em rota.\n\n## Modelo de dados\n- stops, vehicles, routes, route_stops\n\n## Stack sugerida\n- Backend com motor de otimizacao e mapas.', ARRAY['logistica','roteirizacao','rotas']),
('gestao-armazem-wms', 'Gestao de armazem (WMS)', 'Logistica', 'Controle de recebimento, enderecamento e separacao.', E'# Gestao de armazem WMS\n\n## Objetivo\nControlar recebimento, enderecamento, separacao e expedicao.\n\n## Requisitos funcionais\n- FR-01 Recebimento e conferencia de mercadoria.\n- FR-02 Enderecamento por posicao no armazem.\n- FR-03 Separacao (picking) por pedido.\n- FR-04 Inventario e expedicao.\n\n## Modelo de dados\n- items, locations, receipts, picks, shipments\n\n## Stack sugerida\n- Fullstack com coletor de codigo de barras.', ARRAY['logistica','wms','armazem']),
('delivery-comida', 'Delivery de comida', 'Servicos', 'Marketplace de restaurantes com pedido e entrega.', E'# Delivery de comida\n\n## Objetivo\nConectar clientes a restaurantes com pedido, pagamento e entrega.\n\n## Requisitos funcionais\n- FR-01 Cardapio por restaurante com adicionais.\n- FR-02 Carrinho, pagamento e taxa de entrega.\n- FR-03 Acompanhamento do pedido em tempo real.\n- FR-04 Avaliacao de restaurante e entregador.\n\n## Modelo de dados\n- restaurants, menu_items, orders, deliveries\n\n## Stack sugerida\n- Fullstack com tempo real e mapas.', ARRAY['servicos','delivery','comida']),
('salao-beleza', 'Salao de beleza', 'Servicos', 'Agenda de profissionais de beleza com servicos e comissao.', E'# Salao de beleza\n\n## Objetivo\nAgendar servicos de beleza e controlar comissao dos profissionais.\n\n## Requisitos funcionais\n- FR-01 Cadastro de profissionais e servicos.\n- FR-02 Agenda com duracao e prevencao de conflito.\n- FR-03 Comissao por servico realizado.\n- FR-04 Ficha e historico do cliente.\n\n## Modelo de dados\n- professionals, services, bookings, commissions\n\n## Stack sugerida\n- Fullstack com notificacoes.', ARRAY['servicos','beleza','agenda']),
('coworking-reservas', 'Reserva de coworking', 'Servicos', 'Reserva de salas e estacoes com planos e acesso.', E'# Reserva de coworking\n\n## Objetivo\nGerenciar reserva de salas e estacoes com planos e controle de acesso.\n\n## Requisitos funcionais\n- FR-01 Cadastro de espacos e capacidade.\n- FR-02 Reserva por hora ou por plano.\n- FR-03 Check-in e controle de acesso.\n- FR-04 Faturamento por uso e plano.\n\n## Modelo de dados\n- spaces, plans, bookings, checkins\n\n## Stack sugerida\n- Fullstack com cobranca.', ARRAY['servicos','coworking','reservas']),
('oficina-mecanica', 'Oficina mecanica', 'Servicos', 'Ordens de servico com pecas, mao de obra e orcamento.', E'# Oficina mecanica\n\n## Objetivo\nGerenciar ordens de servico com orcamento de pecas e mao de obra.\n\n## Requisitos funcionais\n- FR-01 Cadastro de veiculos e clientes.\n- FR-02 Ordem de servico com itens e mao de obra.\n- FR-03 Aprovacao de orcamento pelo cliente.\n- FR-04 Historico de servicos por veiculo.\n\n## Modelo de dados\n- vehicles, work_orders, parts, labor\n\n## Stack sugerida\n- Fullstack interno.', ARRAY['servicos','oficina','ordens']),
('avaliacao-desempenho', 'Avaliacao de desempenho', 'RH', 'Ciclos de avaliacao com metas, feedback e notas.', E'# Avaliacao de desempenho\n\n## Objetivo\nConduzir ciclos de avaliacao com metas, feedback e notas.\n\n## Requisitos funcionais\n- FR-01 Definicao de ciclos e competencias.\n- FR-02 Autoavaliacao e avaliacao do gestor.\n- FR-03 Feedback 360 graus opcional.\n- FR-04 Relatorio consolidado por colaborador.\n\n## Modelo de dados\n- cycles, competencies, reviews, feedbacks\n\n## Stack sugerida\n- Fullstack SaaS.', ARRAY['rh','desempenho','avaliacao']),
('onboarding-colaborador', 'Onboarding de colaborador', 'RH', 'Trilhas de integracao com tarefas e documentos do novo colaborador.', E'# Onboarding de colaborador\n\n## Objetivo\nIntegrar novos colaboradores com trilhas de tarefas e documentos.\n\n## Requisitos funcionais\n- FR-01 Trilha de onboarding por cargo.\n- FR-02 Tarefas com responsavel e prazo.\n- FR-03 Coleta de documentos e assinaturas.\n- FR-04 Acompanhamento de progresso.\n\n## Modelo de dados\n- journeys, tasks, documents, employees\n\n## Stack sugerida\n- Fullstack interno.', ARRAY['rh','onboarding','integracao']),
('programa-fidelidade', 'Programa de fidelidade', 'Marketing', 'Pontos e recompensas por compra com resgate.', E'# Programa de fidelidade\n\n## Objetivo\nAcumular pontos por compra e permitir resgate de recompensas.\n\n## Requisitos funcionais\n- FR-01 Regras de acumulo de pontos.\n- FR-02 Catalogo de recompensas.\n- FR-03 Resgate e saldo de pontos.\n- FR-04 Niveis de fidelidade.\n\n## Modelo de dados\n- members, points, rewards, redemptions\n\n## Stack sugerida\n- Fullstack SaaS.', ARRAY['marketing','fidelidade','pontos']),
('gestao-redes-sociais', 'Gestao de redes sociais', 'Marketing', 'Agendamento e metricas de posts em multiplas redes.', E'# Gestao de redes sociais\n\n## Objetivo\nAgendar publicacoes e acompanhar metricas em varias redes.\n\n## Requisitos funcionais\n- FR-01 Conexao de contas de redes sociais.\n- FR-02 Calendario e agendamento de posts.\n- FR-03 Publicacao automatica na data agendada.\n- FR-04 Metricas de alcance e engajamento.\n\n## Modelo de dados\n- accounts, posts, schedules, metrics\n\n## Stack sugerida\n- Backend com worker de publicacao.', ARRAY['marketing','social','agendamento']),
('afiliados', 'Programa de afiliados', 'Marketing', 'Links de indicacao com comissao e rastreio de conversao.', E'# Programa de afiliados\n\n## Objetivo\nGerar links de indicacao e pagar comissao por conversao.\n\n## Requisitos funcionais\n- FR-01 Cadastro de afiliados e links unicos.\n- FR-02 Rastreio de clique e conversao.\n- FR-03 Calculo de comissao por regra.\n- FR-04 Repasse e extrato do afiliado.\n\n## Modelo de dados\n- affiliates, links, conversions, payouts\n\n## Stack sugerida\n- Backend com rastreio e ledger.', ARRAY['marketing','afiliados','comissao']),
('gestao-documentos', 'Gestao de documentos (DMS)', 'Produtividade', 'Repositorio de documentos com versoes e permissoes.', E'# Gestao de documentos DMS\n\n## Objetivo\nArmazenar documentos com versionamento, busca e permissoes.\n\n## Requisitos funcionais\n- FR-01 Upload e organizacao em pastas.\n- FR-02 Versionamento de documento.\n- FR-03 Busca por conteudo e metadados.\n- FR-04 Permissao por pasta e documento.\n\n## Modelo de dados\n- folders, documents, versions, permissions\n\n## Stack sugerida\n- Fullstack com storage de objetos.', ARRAY['produtividade','documentos','dms']),
('assinatura-eletronica', 'Assinatura eletronica', 'Produtividade', 'Envio de documentos para assinatura com trilha de auditoria.', E'# Assinatura eletronica\n\n## Objetivo\nEnviar documentos para assinatura com validade e trilha de auditoria.\n\n## Requisitos funcionais\n- FR-01 Upload e definicao de signatarios.\n- FR-02 Ordem de assinatura e lembretes.\n- FR-03 Assinatura com carimbo de tempo.\n- FR-04 Trilha de auditoria e documento final.\n\n## Modelo de dados\n- documents, signers, signatures, audit_trail\n\n## Stack sugerida\n- Backend com hash e trilha imutavel.', ARRAY['produtividade','assinatura','documentos']),
('projetos-gantt', 'Gestao de projetos com Gantt', 'Produtividade', 'Cronograma de projetos com dependencias e marcos.', E'# Gestao de projetos com Gantt\n\n## Objetivo\nPlanejar projetos com cronograma, dependencias e marcos.\n\n## Requisitos funcionais\n- FR-01 Tarefas com inicio, fim e responsavel.\n- FR-02 Dependencias entre tarefas.\n- FR-03 Grafico de Gantt e caminho critico.\n- FR-04 Marcos e percentual concluido.\n\n## Modelo de dados\n- projects, tasks, dependencies, milestones\n\n## Stack sugerida\n- Fullstack colaborativo.', ARRAY['produtividade','projetos','gantt']),
('forum-comunidade', 'Forum e comunidade', 'Social', 'Topicos, respostas e reputacao com moderacao.', E'# Forum e comunidade\n\n## Objetivo\nDiscutir topicos com respostas, votos e reputacao.\n\n## Requisitos funcionais\n- FR-01 Categorias e topicos.\n- FR-02 Respostas com votos.\n- FR-03 Reputacao e distintivos.\n- FR-04 Moderacao e denuncia.\n\n## Modelo de dados\n- categories, topics, posts, votes\n\n## Stack sugerida\n- Fullstack com cache.', ARRAY['social','forum','comunidade']),
('eventos-networking', 'Eventos e networking', 'Social', 'Eventos com inscricao, agenda e conexoes entre participantes.', E'# Eventos e networking\n\n## Objetivo\nOrganizar eventos com inscricao, agenda e conexoes entre participantes.\n\n## Requisitos funcionais\n- FR-01 Cadastro de eventos e sessoes.\n- FR-02 Inscricao e credenciamento.\n- FR-03 Agenda pessoal do participante.\n- FR-04 Conexao e mensagens entre participantes.\n\n## Modelo de dados\n- events, sessions, attendees, connections\n\n## Stack sugerida\n- Fullstack.', ARRAY['social','eventos','networking']),
('ouvidoria', 'Ouvidoria ao cidadao', 'Governo BR', 'Registro e tramitacao de manifestacoes do cidadao.', E'# Ouvidoria ao cidadao\n\n## Objetivo\nReceber e tramitar manifestacoes do cidadao com prazo de resposta.\n\n## Requisitos funcionais\n- FR-01 Registro de manifestacao por tipo.\n- FR-02 Protocolo e acompanhamento pelo cidadao.\n- FR-03 Encaminhamento ao setor responsavel.\n- FR-04 Prazo legal e resposta.\n\n## Modelo de dados\n- manifestations, protocols, departments, responses\n\n## Stack sugerida\n- Fullstack com trilha de auditoria.', ARRAY['governo','brasil','ouvidoria']),
('licitacoes', 'Portal de licitacoes', 'Governo BR', 'Publicacao de editais e recebimento de propostas.', E'# Portal de licitacoes\n\n## Objetivo\nPublicar editais e receber propostas de fornecedores.\n\n## Requisitos funcionais\n- FR-01 Cadastro de editais com prazos.\n- FR-02 Habilitacao de fornecedores.\n- FR-03 Envio e abertura de propostas.\n- FR-04 Resultado e ata publica.\n\n## Modelo de dados\n- tenders, suppliers, proposals, awards\n\n## Stack sugerida\n- Fullstack com trilha de auditoria.', ARRAY['governo','brasil','licitacoes']),
('gestao-locacao', 'Gestao de locacao', 'Imobiliario', 'Contratos de aluguel com boletos, reajuste e vistoria.', E'# Gestao de locacao\n\n## Objetivo\nAdministrar contratos de aluguel com cobranca e reajuste.\n\n## Requisitos funcionais\n- FR-01 Contrato de locacao com indice de reajuste.\n- FR-02 Geracao de cobranca mensal.\n- FR-03 Vistoria de entrada e saida.\n- FR-04 Repasse ao proprietario.\n\n## Modelo de dados\n- properties, contracts, charges, inspections\n\n## Stack sugerida\n- Fullstack com worker de cobranca.', ARRAY['imobiliario','locacao','aluguel']),
('condominio-gestao', 'Gestao de condominio', 'Imobiliario', 'Portal do condominio com taxas, reservas e comunicados.', E'# Gestao de condominio\n\n## Objetivo\nGerenciar unidades, taxas, reservas de areas e comunicados.\n\n## Requisitos funcionais\n- FR-01 Cadastro de unidades e moradores.\n- FR-02 Cobranca de taxa condominial.\n- FR-03 Reserva de areas comuns.\n- FR-04 Comunicados e assembleias.\n\n## Modelo de dados\n- units, residents, charges, reservations\n\n## Stack sugerida\n- Fullstack com cobranca.', ARRAY['imobiliario','condominio','gestao']),
('podcast-hosting', 'Hospedagem de podcast', 'Conteudo', 'Publicacao de episodios com feed RSS e metricas.', E'# Hospedagem de podcast\n\n## Objetivo\nHospedar episodios de podcast com feed RSS e metricas de audiencia.\n\n## Requisitos funcionais\n- FR-01 Upload de episodio e metadados.\n- FR-02 Geracao de feed RSS.\n- FR-03 Player publico por programa.\n- FR-04 Metricas de download e escuta.\n\n## Modelo de dados\n- shows, episodes, media, plays\n\n## Stack sugerida\n- Backend com storage de objetos e CDN.', ARRAY['conteudo','podcast','rss']),
('streaming-video', 'Streaming de video (VOD)', 'Conteudo', 'Catalogo de videos sob demanda com planos e player.', E'# Streaming de video VOD\n\n## Objetivo\nOferecer catalogo de videos sob demanda com planos e player.\n\n## Requisitos funcionais\n- FR-01 Upload e transcodificacao de video.\n- FR-02 Catalogo com categorias e busca.\n- FR-03 Player com controle de acesso por plano.\n- FR-04 Continuar assistindo e historico.\n\n## Modelo de dados\n- videos, categories, plans, watch_progress\n\n## Stack sugerida\n- Backend com transcodificacao e CDN.', ARRAY['conteudo','video','streaming']),
('escritorio-advocacia', 'Gestao de escritorio de advocacia', 'Juridico', 'Processos, prazos e clientes de um escritorio de advocacia.', E'# Gestao de escritorio de advocacia\n\n## Objetivo\nGerenciar processos, prazos, clientes e horas de um escritorio.\n\n## Requisitos funcionais\n- FR-01 Cadastro de clientes e processos.\n- FR-02 Controle de prazos e audiencias.\n- FR-03 Registro de horas e honorarios.\n- FR-04 Documentos por processo.\n\n## Modelo de dados\n- clients, cases, deadlines, timesheets\n\n## Stack sugerida\n- Fullstack interno.', ARRAY['juridico','advocacia','processos']),
('contratos-clm', 'Gestao de contratos (CLM)', 'Juridico', 'Ciclo de vida de contratos com prazos e renovacao.', E'# Gestao de contratos CLM\n\n## Objetivo\nGerenciar o ciclo de vida de contratos da elaboracao a renovacao.\n\n## Requisitos funcionais\n- FR-01 Repositorio de contratos com partes e valores.\n- FR-02 Fluxo de aprovacao e assinatura.\n- FR-03 Alertas de vencimento e renovacao.\n- FR-04 Clausulas e obrigacoes por contrato.\n\n## Modelo de dados\n- contracts, parties, clauses, obligations\n\n## Stack sugerida\n- Fullstack com alertas.', ARRAY['juridico','contratos','clm']),
('gestao-fazenda', 'Gestao de fazenda', 'Agro', 'Talhoes, safras, insumos e custos de producao rural.', E'# Gestao de fazenda\n\n## Objetivo\nControlar talhoes, safras, insumos e custos de producao.\n\n## Requisitos funcionais\n- FR-01 Cadastro de talhoes e culturas.\n- FR-02 Planejamento de safra e plantio.\n- FR-03 Registro de insumos e aplicacoes.\n- FR-04 Custo e produtividade por talhao.\n\n## Modelo de dados\n- fields, crops, seasons, inputs\n\n## Stack sugerida\n- Fullstack interno.', ARRAY['agro','fazenda','safra']),
('rastreabilidade-agro', 'Rastreabilidade agricola', 'Agro', 'Rastreio do lote da origem ao ponto de venda.', E'# Rastreabilidade agricola\n\n## Objetivo\nRastrear lotes de producao da origem ao ponto de venda.\n\n## Requisitos funcionais\n- FR-01 Registro de lote com origem e produtor.\n- FR-02 Eventos de manejo e colheita.\n- FR-03 Cadeia de custodia ate a venda.\n- FR-04 Consulta publica por codigo do lote.\n\n## Modelo de dados\n- lots, events, custody, products\n\n## Stack sugerida\n- Backend event-driven.', ARRAY['agro','rastreabilidade','lote']),
('reservas-hotel', 'Reservas de hotel', 'Turismo', 'Motor de reservas com quartos, tarifas e disponibilidade.', E'# Reservas de hotel\n\n## Objetivo\nGerenciar reservas de quartos com tarifas e disponibilidade.\n\n## Requisitos funcionais\n- FR-01 Cadastro de quartos e tipos.\n- FR-02 Tarifas por periodo e disponibilidade.\n- FR-03 Reserva com check-in e check-out.\n- FR-04 Pagamento e politica de cancelamento.\n\n## Modelo de dados\n- rooms, rates, reservations, guests\n\n## Stack sugerida\n- Fullstack com motor de disponibilidade.', ARRAY['turismo','hotel','reservas']),
('roteiros-turismo', 'Roteiros de viagem', 'Turismo', 'Montagem de roteiros com atracoes, dias e reservas.', E'# Roteiros de viagem\n\n## Objetivo\nMontar roteiros de viagem com atracoes, dias e reservas.\n\n## Requisitos funcionais\n- FR-01 Catalogo de destinos e atracoes.\n- FR-02 Montagem de roteiro por dia.\n- FR-03 Reserva de atividades e passeios.\n- FR-04 Compartilhamento do roteiro.\n\n## Modelo de dados\n- destinations, attractions, itineraries, bookings\n\n## Stack sugerida\n- Fullstack.', ARRAY['turismo','roteiros','viagem']),
('cardapio-digital', 'Cardapio digital por QR', 'Alimentacao', 'Cardapio acessado por QR Code com pedido na mesa.', E'# Cardapio digital por QR\n\n## Objetivo\nExibir cardapio por QR Code e receber pedido na mesa.\n\n## Requisitos funcionais\n- FR-01 Cardapio por mesa acessado via QR Code.\n- FR-02 Pedido na mesa com adicionais.\n- FR-03 Envio do pedido a cozinha.\n- FR-04 Fechamento de conta por mesa.\n\n## Modelo de dados\n- tables, menu_items, orders, order_items\n\n## Stack sugerida\n- Fullstack com tempo real.', ARRAY['alimentacao','cardapio','qrcode']),
('gestao-academia', 'Gestao de academia', 'Esportes', 'Planos, matriculas, treinos e acesso da academia.', E'# Gestao de academia\n\n## Objetivo\nGerenciar planos, matriculas, treinos e acesso de alunos.\n\n## Requisitos funcionais\n- FR-01 Planos e matricula com cobranca recorrente.\n- FR-02 Controle de acesso na catraca.\n- FR-03 Fichas de treino por aluno.\n- FR-04 Frequencia e evasao.\n\n## Modelo de dados\n- members, plans, workouts, checkins\n\n## Stack sugerida\n- Fullstack com cobranca.', ARRAY['esportes','academia','treino']),
('agendamento-quadras', 'Aluguel de quadras', 'Esportes', 'Reserva de quadras esportivas por horario e pagamento.', E'# Aluguel de quadras\n\n## Objetivo\nReservar quadras esportivas por horario com pagamento.\n\n## Requisitos funcionais\n- FR-01 Cadastro de quadras e horarios.\n- FR-02 Reserva por horario com prevencao de conflito.\n- FR-03 Pagamento e politica de cancelamento.\n- FR-04 Reserva recorrente e mensalista.\n\n## Modelo de dados\n- courts, slots, bookings, payments\n\n## Stack sugerida\n- Fullstack com cobranca.', ARRAY['esportes','quadras','reservas']),
('gestao-doacoes', 'Gestao de doacoes (ONG)', 'ONG', 'Doadores, campanhas e prestacao de contas de uma ONG.', E'# Gestao de doacoes ONG\n\n## Objetivo\nGerenciar doadores, campanhas e prestacao de contas.\n\n## Requisitos funcionais\n- FR-01 Cadastro de doadores e campanhas.\n- FR-02 Doacao unica e recorrente.\n- FR-03 Recibo e comprovante de doacao.\n- FR-04 Prestacao de contas por campanha.\n\n## Modelo de dados\n- donors, campaigns, donations, receipts\n\n## Stack sugerida\n- Fullstack com cobranca.', ARRAY['ong','doacoes','campanhas'])
ON CONFLICT (slug) DO NOTHING;
