/**
 * githubPush — Triggered when a tenant accepts a project.
 *
 * Flow:
 * 1. Check tenant has GitHub App installed
 * 2. Idempotency check: skip if project_github_repos already exists
 * 3. Create repository (private, auto_init=true)
 * 4. Ensure 3 branches: main, staging, dev
 * 5. Push all apps/ files to branch "dev"
 * 6. Save to project_github_repos
 * 7. Add dialogue entry so portal shows the repo link
 */

import { pool } from "../db/client.js";
import {
  createRepository,
  ensureThreeBranches,
  pushProjectFiles,
} from "./github.js";

const PROJECT_FILES_ROOT = (process.env.PROJECT_FILES_ROOT ?? "/shared/uploads").trim();

// Slugify project title to a valid GitHub repo name
function toRepoName(title: string): string {
  const base = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 50);
  // Append short random suffix to avoid collisions
  const suffix = Math.random().toString(36).slice(2, 6);
  return `${base || "genesis-project"}-${suffix}`;
}

export async function pushProjectToGitHub(projectId: string): Promise<void> {
  const client = await pool.connect();
  try {
    // ── 1. Load project + tenant ──────────────────────────────────────────────
    const projRes = await client.query(
      `SELECT p.id, p.title, p.tenant_id, p.created_by,
              gi.installation_id, gi.github_login, gi.installation_type
       FROM projects p
       LEFT JOIN tenant_github_installations gi ON gi.tenant_id = p.tenant_id
       WHERE p.id = $1`,
      [projectId],
    );
    const row = projRes.rows[0];
    if (!row) { console.warn(`[GitHubPush] Project ${projectId} not found`); return; }
    if (!row.installation_id) {
      console.log(`[GitHubPush] Tenant has no GitHub App installation — skipping`);
      return;
    }

    // ── 2. Idempotency ────────────────────────────────────────────────────────
    const existing = await client.query(
      "SELECT repo_url FROM project_github_repos WHERE project_id = $1",
      [projectId],
    );
    if (existing.rows.length > 0) {
      console.log(`[GitHubPush] Repo already exists for ${projectId}: ${existing.rows[0].repo_url}`);
      return;
    }

    const installationId = row.installation_id as number;
    const owner = row.github_login as string;
    const repoName = toRepoName((row.title as string) ?? "genesis-project");

    console.log(`[GitHubPush] Creating repo ${owner}/${repoName} for project ${projectId}`);

    // ── 3. Create repo ────────────────────────────────────────────────────────
    const { url: repoUrl, fullName } = await createRepository(installationId, {
      org: row.installation_type === "Organization" ? owner : undefined,
      name: repoName,
      description: `Generated by Zentriz Genesis — ${row.title ?? projectId}`,
      private: true,
      autoInit: true,
    });

    // ── 4. 3 branches ─────────────────────────────────────────────────────────
    await ensureThreeBranches(installationId, owner, repoName);

    // ── 5. Push files to dev ──────────────────────────────────────────────────
    const { sha: shaDevResult, fileCount } = await pushProjectFiles(
      installationId, owner, repoName, "dev",
      PROJECT_FILES_ROOT, projectId,
    );

    // ── 6. Save to DB ─────────────────────────────────────────────────────────
    const cloneUrl = repoUrl;
    await client.query(
      `INSERT INTO project_github_repos
         (project_id, repo_name, repo_full_name, repo_url, clone_url, default_branch, pushed_at, sha_dev)
       VALUES ($1, $2, $3, $4, $5, 'main', now(), $6)
       ON CONFLICT (project_id) DO UPDATE
         SET pushed_at = now(), sha_dev = $6`,
      [projectId, repoName, fullName, `https://github.com/${fullName}`, cloneUrl, shaDevResult],
    );

    // ── 7. Dialogue entry ─────────────────────────────────────────────────────
    await client.query(
      `INSERT INTO project_dialogue (project_id, from_agent, to_agent, event_type, summary_human)
       VALUES ($1, 'system', 'system', 'step', $2)`,
      [projectId, `Repositório GitHub criado: https://github.com/${fullName} — ${fileCount} arquivos enviados para branch dev.`],
    );

    console.log(`[GitHubPush] ✓ ${fullName} — ${fileCount} files pushed to dev (${shaDevResult.slice(0, 8)})`);
  } catch (err) {
    console.error(`[GitHubPush] Failed for project ${projectId}:`, err);
    // Fire-and-forget: never throw — must not fail the accept request
  } finally {
    client.release();
  }
}
